# conda dependencies for building docs
channels:
  - conda-forge
dependencies:
  - pip
  - sphinx
  - sphinx-copybutton
  - sphinx_rtd_theme
  - rpyc
  - numpy
  - pyqtgraph
  - pyqt6
  - h5py
  - pyvisa
  - qtpy